"on":
    push:
        branches:
            - main
name: Deploy to captain-mcp
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: captain-mcp
                PORTER_CLUSTER: "5167"
                PORTER_DEPLOYMENT_TARGET_ID: e63cc47d-c0f9-42ff-9a4c-71b99a6ff9ae
                PORTER_HOST: https://dashboard.porter.run
                PORTER_PROJECT: "17299"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_17299_17794 }}
